### ISSUE TITLE
training taking too long on transfer items from yolov7-seg.pt

### ISSUE THREAD

**Issue by Wong-denis** [laitathei/YOLOv7-Pytorch-Segmentation#1]
Hello! I'm a newbie on YOLO
I finally pull off the implementation of training and predicting custom dataset, thanks to the video tutorial.

However, it always take me more than 20min to transfer items from yolov7-seg.pt when training.
![Screenshot from 2022-10-19 17-20-04](https://user-images.githubusercontent.com/57944444/196655152-b04f0d47-ec4c-43eb-9713-ca48f6ec681c.png)

Here is the command I wrote
![Screenshot from 2022-10-19 17-38-35](https://user-images.githubusercontent.com/57944444/196655880-e30c6cc5-f135-4832-88c1-c310780bb0d1.png)

It seems like you don't have this problem in the video.
Please tell what to do if you know how to fix it

**Comment by laitathei** [comment]
I think the problem may come from the dataset size and your hardware setting problem. In my demo case, i am using very small dataset and GeForce RTX 3060 GPU. Can you tell me about your dataset size and hardware setup?

**Comment by Wong-denis** [comment]
Thank you so much for replying!
I'm using RTX3050 GPU. 
And below is my datasize
train: 98 images  (512x512)
valid: 14 images (512x512)

**Comment by laitathei** [comment]
your setting and data size are quite similar to mine. I didn't have any idea about it. Maybe you raise an issue on the original yolov7 repo
