### ISSUE TITLE
Can you provied Weights files? 

### ISSUE THREAD

**Issue by Deo-ahn** [laitathei/YOLOv7-Pytorch-Segmentation#2]
Hi, 
Thank you for your nice works,

Now I want to try just for inference the video file and stream camera first. 

So for the inference , IS there any weight file that you've already got from COCO or other datasets?

**Comment by laitathei** [comment]
you can check the origin repo from the yolov7 author. He provided the weight file from the COCO dataset
the link is https://github.com/WongKinYiu/yolov7/releases/tag/v0.1
